### ISSUE TITLE
LED Housing alternatives? 

### ISSUE THREAD

**Issue by jay-jey** [stevenbennett/DIYson#1]
Hello, it seems that the housing of the LED is not longer availible, do you know any other housing that is working with the Lens and LED? There are so many different options, it is one of the smallest part but I think very important. Hope you cloud help me out with this. 
BTW, very cool project. 

FP15948_HEKLA-H 

https://www.mouser.com/ProductDetail/Ledil/FP15948_HEKLA-H?qs=0lQeLiL1qybeRTKyjbFVcA%3D%3D

**Comment by stevenbennett** [comment]
@jay-jey Hold tight for a bit because I've recently changed the LED and corresponding LED housing (due to issues like this where components abruptly become unavailable). Once I have the new LED tested I will update the BOM and this issue :)

**Comment by stevenbennett** [comment]
@jay-jey Just updated the parts list with the new LED housing, and it's in stock woo!

**Comment by stevenbennett** [comment]
It's this one btw: https://www.mouser.com/ProductDetail/Ledil/F15256_HEKLA-SOCKET-D?qs=o2C7DKDMuStSi5P8paemqw%3D%3D
