### ISSUE TITLE
[DIYson] Missing PCB Schematic/Electronic Designs

### ISSUE THREAD

**Issue by Joseph0M** [stevenbennett/DIYson#19]
As seen in Video #7, It seems that the PCB design is absent from the files. I am sure the design will change from now, but it would be nice if the community could have a crack at the electronics. Also, the board outline + dimensions would be a nice addition.

**Comment by stevenbennett** [comment]
@Joseph0M I would really like to put the PCB files up for folks to tinker with, but I need a little bit more time before I'm ready to share it/have people contribute to it.
