### ISSUE TITLE
Belts width

### ISSUE THREAD

**Issue by jay-jey** [stevenbennett/DIYson#2]
Hello, 
I know the project is in early stage and not finsished at a all, but I allready printed some things out to tinker around a little bit. And I noticed that the openbuild belts are 5mm width. In 3D printing the belts are normaly 6mm. I think this could lead to some trouble, because I thing many people will have problem with this.

**Comment by stevenbennett** [comment]
Fair point, it would be ideal to use a 6mm belt since that's what 3D printing enthusiasts will have on hand. Unfortunately the 6mm belt is to wide to fit within the aluminum rail channels (technically it does fit since the channel is just over 6mm wide, but the belt will tend to rub).
