### ISSUE TITLE
.F3D Files

### ISSUE THREAD

**Issue by fgutep** [stevenbennett/DIYson#3]
Steven, it would be great to get the original . F3D files to tweak the models more easily in Fusion 360. If you could share them with us, it would be much appreciated. Thank you very much.

**Comment by stevenbennett** [comment]
Good idea. I think I will hold off on sharing all of the parts (most of them are very early WIP), but I just added the carriage file. Let me know if there are any others that you need right now, otherwise I will upload all files closer to a "v1" release.
