### ISSUE TITLE
LED Flicker

### ISSUE THREAD

**Issue by zamu-flowerpot** [stevenbennett/DIYson#5]
Just watched your [latest video on YT (as of 2023/01/05)](https://www.youtube.com/watch?v=Emohi3FtTuM) and noticed that you are trying to power through a technical problem instead of using a technical solution!

LED Flicker is caused by having the PWM being out of sync with the camera's shutter speed. Instead of me trying to regurgitate how to fix this, check out RED digital camera's guide on flicker-free video [tutorial](https://www.red.com/red-101/flicker-free-video-tutorial).

So essentially, change either the camera shutter speed to something that is a multiple of 1000 (and whatever the stepping is) or change the LED's PWM and stepping to be a multiple of the camera shutter speed.

**Comment by stevenbennett** [comment]
@zamu-flowerpot Thanks for the suggestion and guide, always good to have a walkthrough from an expert source.

This solution has been suggested a lot, and as far as I can tell the easiest way to test it is to change shutter speed from 29.97fps to 25fps (so that it is a divisor of 1000(hz)). Unfortunately this didn't work. Am I missing something? My next test will be to programmatically try every frequency from 1-1000 and see if there are any that eliminate banding.

**Comment by DimaVIII** [comment]
@stevenbennett Here is your solution to the flickering problem. https://www.youtube.com/watch?v=DdToSNgPnO8&list=WL&index=64

You just need to go crazy high on the frequency, 150-300kHz seams to do the trick. You will need a [MOSFET](https://en.wikipedia.org/wiki/MOSFET) to drive it.
There is also the possibility that you need to change your microcontroller to a ESP32 (which is also quite small and has wifi + Bluetooth build in and costs around 2$) as your current one may not able to output such high frequency. This should solve also the power supply humming as this high frequencies can't be heard.

**Comment by DimaVIII** [comment]
Here is a technical guide on how to dim analog LEDs. 
https://quinled.info/2019/12/19/quinled-quad-hardware-guide-v1r6/

**Comment by MarcoMobilio** [comment]
small comment on DimaVIII suggestion on using a mosfet to drive the led. If you are using a mosfet, can't you move the electronics back to the base? You need to carry to the lamp only ground and drain from the mosfet up to the led, like you are doing now with power. I know your custom PCB looks nice, but that would simplify the electronic distribution and give you more wiggle room.

**Comment by B0rax** [comment]
> small comment on DimaVIII suggestion on using a mosfet to drive the led. If you are using a mosfet, can't you move the electronics back to the base? You need to carry to the lamp only ground and drain from the mosfet up to the led, like you are doing now with power. I know your custom PCB looks nice, but that would simplify the electronic distribution and give you more wiggle room.

you would still need wiring for the buttons...

**Comment by Joseph0M** [comment]
You also would not be able to add hardware like ambient light and time of flight sensors required for some of the more advanced features.

**Comment by MarcoMobilio** [comment]
Aaaaaand… I’m an idiot, you are both right, obviously 😅

**Comment by stevenbennett** [comment]
Solved! 

See:
203d19140b4c9bcb8ad206546123c115a8837234 and https://www.youtube.com/watch?v=mTmQzcG-7h4
